### PR TITLE
Fix partially/overly applied type variables in entryfuncs file

### LINKED ISSUE #357: Entryfuncs file should not accept partially applied type applications
Currently giving a partially applied function definition in the file supplied to `--entry-funcs` results in the monomorphiser crashing. This should be checked and banned in `cogent/src/Cogent/Glue.hs:readEntryFuncs`

### PR DESCRIPTION
**Pull request by emmet-m**
As per title

Closes #357

### CODE REVIEW

**Review by vjackson725 — APPROVED** [review]
Looks good.

**Comment by vjackson725** [comment]
Hmm; the `getFnName` call seems to be the problem
```
                let nargs = SF.numTypeVars $ 
                      case find (\tl -> getFnName tl == fnName) tced of
                          Just f  -> f
                          Nothing -> __impossible "Could not find function in top level declarations"
```

File: cogent/Main.hs [hunk 1]
```diff
@@ -743,8 +743,15 @@ parseArgs args = case getOpt' Permute options args of
...
       let stg = STGMono
       putProgressLn "Monomorphising..."
-      entryFuncs <- T.forM __cogent_entry_funcs $
-                      return . (,empty) <=< (readEntryFuncs tced tcst typedefs fts) <=< return . parseEntryFuncs <=< readFile
+      efuns <- T.forM __cogent_entry_funcs $
+                            return . (,empty) <=< (readEntryFuncs tced tcst typedefs fts) <=< return . parseEntryFuncs <=< readFile
+      entryFuncs <- case efuns of
+                      Nothing -> return Nothing
+                      Just (Nothing, _) -> do
+                        exitFailure
```
Comment (zilinc) [inline cogent/Main.hs:751]: Wouldn't `exitFailure` throw an exception immediately?

File: cogent/src/Cogent/Glue.hs [hunk 2]
```diff
@@ -837,25 +837,57 @@ readEntryFuncs :: [SF.TopLevel TC.DepType TC.TypedPatn TC.TypedExpr]
                -> Last (DS.Typedefs, DS.Constants, [CC.CoreConst CC.UntypedExpr])
                -> M.Map FunName (CC.FunctionType VarName)
                -> [String]
-               -> IO (MN.FunMono VarName)
+               -> IO (Maybe (MN.FunMono VarName))
 readEntryFuncs tced tcState dsState ftypes lns
-  = foldM (\m ln -> readEntryFunc ln >>= \(fn,inst) -> return $ updateFunMono m fn inst) M.empty lns
+  = foldM run (Just M.empty) lns
   where
+    run md ln =
```
Comment (zilinc) [inline cogent/src/Cogent/Glue.hs:844]: It can be defined in a monadic way, which might be more concise and more readable.

File: cogent/src/Cogent/Glue.hs [hunk 3]
```diff
@@ -837,25 +837,57 @@ readEntryFuncs :: [SF.TopLevel TC.DepType TC.TypedPatn TC.TypedExpr]
...
+                              optMsg (nargs > L.length targs))
+                else do
+                  inst <- forM targs $ \mt ->
+                            case mt of
+                              Nothing -> throwError "Use of wildcard disallowed in --entry-funcs file"
+                              Just t  -> flip runReaderT (DefnState Vec.Nil []) $
+                                          flip runReaderT (MonoState (([], []), Nothing))
+                                                          (lift . tcType >=> lift . desugarType >=> monoType $ t)
+                  return (fnName, inst)
+      case er of Left s  -> putStrLn ("\nError: " ++ s) >> return Nothing
```
Comment (zilinc) [inline cogent/src/Cogent/Glue.hs:881]: it should go to stderr.

File: cogent/src/Cogent/Glue.hs [hunk 4]
```diff
@@ -837,25 +837,57 @@ readEntryFuncs :: [SF.TopLevel TC.DepType TC.TypedPatn TC.TypedExpr]
...
+
+    isFnName (SF.FunDef fn _ _) n = fn == n
+    isFnName (SF.AbsDec fn _) n = fn == n
+    isFnName _ _ = False
+
+    optMsg :: Bool -> String
+    optMsg b = if b then
+                "Functions in a --entry-funcs file cannot be partially applied."
+               else
+                "Did you apply too many type arguments?"
```
Comment (zilinc) [inline cogent/src/Cogent/Glue.hs:892]: "Did you apply too many type arguments in a --entry-funcs file?"

File: cogent/src/Cogent/Glue.hs (hunk 3 above)
Comment (vjackson725) [reply cogent/src/Cogent/Glue.hs:881]: do we have a standard way of doing this?

Comment (zilinc) [reply cogent/src/Cogent/Glue.hs:878]: No, I just used ` hPutStrLn stderr`.

File: cogent/Main.hs [hunk 5]
```diff
@@ -743,8 +743,15 @@ parseArgs args = case getOpt' Permute options args of
     mono cmds simpled ctygen source tced tcst typedefs fts buildinfo log = do
       let stg = STGMono
       putProgressLn "Monomorphising..."
-      entryFuncs <- T.forM __cogent_entry_funcs $
-                      return . (,empty) <=< (readEntryFuncs tced tcst typedefs fts) <=< return . parseEntryFuncs <=< readFile
+      efuns <- T.forM __cogent_entry_funcs $
+                            return . (,empty) <=< (readEntryFuncs tced tcst typedefs fts) <=< return . parseEntryFuncs <=< readFile
```
Comment (zilinc) [inline cogent/Main.hs:747]: Indentation

File: cogent/src/Cogent/Glue.hs [hunk 6]
```diff
@@ -837,25 +837,53 @@ readEntryFuncs :: [SF.TopLevel TC.DepType TC.TypedPatn TC.TypedExpr]
...
+                              fnName ++ " (" ++ show nargs ++
+                              ") does not match amount specified in --entry-funcs file (" ++
+                              show (L.length targs) ++ ").\n" ++
+                              optMsg (nargs > L.length targs))
+                else do
+                  inst <- forM targs $ \mt ->
+                            case mt of
+                              Nothing -> throwError "Use of wildcard disallowed in --entry-funcs file"
+                              Just t  -> flip runReaderT (DefnState Vec.Nil []) $
+                                          flip runReaderT (MonoState (([], []), Nothing))
```
Comment (zilinc) [inline cogent/src/Cogent/Glue.hs:875]: Indentation.. this one-column indentation looks weird.

File: cogent/src/Cogent/Glue.hs [hunk 7]
```diff
@@ -837,25 +837,53 @@ readEntryFuncs :: [SF.TopLevel TC.DepType TC.TypedPatn TC.TypedExpr]
...
+      case er of Left s  -> putStrLn ("\nError: " ++ s) >> return Nothing
+                 Right r -> return $ Just $ (fst r,) (snd r, [])
+
+    isFnName n (SF.FunDef fn _ _) = fn == n
+    isFnName n (SF.AbsDec fn _) = fn == n
+    isFnName _ _ = False
+
+    optMsg :: Bool -> String
+    optMsg b = if b then
+                "Functions in a --entry-funcs file cannot be partially applied."
```
Comment (zilinc) [inline cogent/src/Cogent/Glue.hs:887]: and these one-column indentations..
